server:
  port: 8500
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    displayRequestDuration: true
    disable-swagger-default-url: true
    csrf:
      enabled: true
    operationsSorter: method #For sorting endpoints by http methods
    tagsSorter: alpha #For sorting tags alphabetically
  api-docs:
    path: /api

# Spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson: 
    default-property-inclusion: NON_NULL

  datasource:
    name: customer-service
    ### In memory H2 connection string
    #jdbc-url: jdbc:h2:mem:customerservice;Mode=postgreSQL
    #username: sa
    # It needs to be empty for h2 (enter sa into h2-console)
    #password: # It needs to be empty for h2
    #type: # It needs to be empty for h2
    #driver-class-name: org.h2.Driver #it has to be populated to avoid "Failed to load driver in either of HikariConfig class loader or Thread context classloader" error
    ### PostgreSQL
    jdbc-url: jdbc:postgresql://localhost:5432/customerservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    tlsEnabled: true

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    pageable:
      page-size: 100

  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true

hibernate:
  bytecode:
    provider: none

management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health: 
    circuitbreakers: 
      enabled: true

---
# need this block for local build even though some params can be left empty
global:
  datasource:
    truststore:
      location: /tmp/postgre.jks #fake placeholder value to avoid local build error
      password:
      content:
      type: JKS
